import type { RecordData, LeaveData, StudentData } from '@/types/record';

export const mockMovementData: RecordData[] = [
    {
        id: '1',
        period: '7교시',
        teacher: '이정하',
        location: '베르실 7',
        count: '7명',
        students: ['1410 윤도훈', '1410 윤도훈', '1410 윤도훈', '1410 윤도훈'],
        reason: '전공동아리',
    },
    {
        id: '2',
        period: '7교시',
        teacher: '이정하',
        location: '베르실 7',
        count: '7명',
        students: ['1410 윤도훈', '1410 윤도훈', '1410 윤도훈', '1410 윤도훈'],
        reason: '전공동아리',
    },
    {
        id: '3',
        period: '7교시',
        teacher: '이정하',
        location: '베르실 7',
        count: '7명',
        students: ['1410 윤도훈', '1410 윤도훈', '1410 윤도훈', '1410 윤도훈'],
        reason: '전공동아리',
    },
];

export const mockLeaveData: LeaveData[] = [
    {
        id: '1',
        studentInfo: '1101 공덕현',
        time: '8교시~11교시',
        handlingTeacher: '이정하',
    },
    {
        id: '2',
        studentInfo: '1101 공덕현',
        time: '8교시~11교시',
        handlingTeacher: '이정하',
    },
    {
        id: '3',
        studentInfo: '1101 공덕현',
        time: '8교시~11교시',
        handlingTeacher: '이정하',
    },
];

export const mockStudentData: StudentData[] = [
    {
        id: '1',
        studentInfo: '1101 공덕현',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '2',
        studentInfo: '1102 김민수',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '3',
        studentInfo: '1103 박서준',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '4',
        studentInfo: '1103 박서준',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '5',
        studentInfo: '1103 박서준',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '6',
        studentInfo: '1103 박서준',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '7',
        studentInfo: '1103 박서준',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '8',
        studentInfo: '1103 박서준',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '9',
        studentInfo: '1103 박서준',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '10',
        studentInfo: '1103 박서준',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },
    {
        id: '11',
        studentInfo: '1103 박서준',
        period5: '방과후',
        period6: '이석',
        period7: '이석',
        period89: '이석',
        period1011: '이석',
    },

];
